# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kulbir Singh Ahluwalia
name: Kulbir Singh Ahluwalia
position: PhD Candidate
email: ksa5@illinois.edu
description: >-
  I'm Kulbir Singh Ahluwalia, a Ph.D. candidate in Computer Science at the University of Illinois, Urbana-Champaign ([UIUC](https://illinois.edu/)),
  focusing on natural language grounding for agricultural robots to advance this critical field. I am fortunate to be mentored by
  [Prof. Girish Chowdhary](http://daslab.illinois.edu) and [Prof. Julia Hockenmaier](https://hmr-lab.github.io).
  My academic foundation includes a Master of Engineering in Robotics from the University of Maryland, where I gained expertise in robotic systems and physics simulations.
  Recently, during my summer internship at EarthSense, Inc., I contributed to developing a natural language-conditioned waypoint generation pipeline.
  My technical skills include Robot Operating System (ROS) and implementing SOTA NLP and CV pipelines for Mobile Manipulators.
  I also co-developed the [CS-498-GC Mobile Robotics course](https://kulbir-singh-ahluwalia.com/cs498gc/fa25/) with Prof. Chowdhary.
  My long-term life goal is scaling up Physical AI for advancing humanity.  





# description: >- # this means to ignore newlines until "baseurl:"
#     I'm Kulbir Singh Ahluwalia, a Ph.D. candidate at the University of Illinois, Urbana-Champaign ([UIUC](https://illinois.edu/)). I am working with Professor Girish Chowdhary and Professor Julia Hockenmaier. My research involves natural language grounding for mobile robots. I graduated with my Master's in Robotics from the University of Maryland where I worked with Professor Pratap Tokekar and Professor Ryan Williams on "Pasture Monitoring in Simulated Environments". 

    
baseurl: ""
url: "https://kulbir-singh-ahluwalia.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Kulbir_Singh_
github_username: kulbir-ahluwalia
linkedin_name: kulbir-ahluwalia
google_scholar: rXq-2HYAAAAJ
orcid_id: "0009-0009-6793-8566"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap


sass:
  style: compact


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
